---
addusers:
  etcd:
    name: etcd
    comment: "Etcd user"
    create_home: yes
    home: "{{ etcd_data_dir }}"
    system: yes
    shell: /bin/nologin
  kube:
    name: kube
    comment: "Kubernetes user"
    shell: /sbin/nologin
    home: /local/kube
    system: yes
    group: "{{ kube_cert_group }}"
    create_home: no
