
# Osquery
- src: https://github.com/apolloclark/ansible-role-osquery.git
  name: osquery
  version: 7fb6547b8813a3d51d0f327eb2fdb54c1031177d

# Docker
- src: https://github.com/angstwad/docker.ubuntu.git
  name: docker
  version: v3.5.2

# Netplan
- src: https://github.com/mrlesmithjr/ansible-netplan.git
  name: netplan
  version: 371fc43d98f7f92f4aaf2b7a50f21ff5cb2d229c
