---
ood_source_version: "v1.7.6"

# Cluster configuration
ood_cluster_config_dir: /etc/ood/config/clusters.d
ood_cluster_title: "NVIDIA DeepOps Cluster"
ood_cluster_name: "deepops"         # has to match Slurm cluster name
ood_install_linuxhost_adapter: yes

# List of extra OOD "apps" to install
ood_install_apps:
  bc_osc_codeserver:
    repo: https://github.com/OSC/bc_osc_codeserver.git
    dest: /var/www/ood/apps/sys
    version: gtc

# Virtual Desktop app configuration
ood_desktops_dir: /etc/ood/config/apps/bc_desktop
ood_desktop_app_title: "NVIDIA DeepOps Desktop"
ood_desktop_app_dir: /var/www/ood/apps/sys/bc_desktop

# VS Code Server app configuration
ood_codeserver_app_dir: /var/www/ood/apps/sys/bc_osc_codeserver
ood_codeserver_app_def-gpus: 1
ood_codeserver_app_cpus-per-gpu: 4
ood_codeserver_app_mem-per-gpu: 16G

# Linuxhost adapter configuration
singularity_image_dir: /mnt/shared/singularity-images
ood_linuxhost_adapter_script: |
  #!/bin/bash
  set -e

  PAM_UID=$(id -u "${PAM_USER}")

  if [ "${PAM_SERVICE}" = "sshd" -a "${PAM_UID}" -ge 1000 ]; then
          /usr/bin/systemctl set-property "user-${PAM_UID}.slice" \
                  MemoryAccounting=true MemoryLimit=64G \
                  CPUAccounting=true \
                  CPUQuota=700%
  fi
ood_linuxhost_adapter_config: |
  ---
  v2:
    metadata:
      title: "NVIDIA DeepOps Cluster Login Node"
      hidden: true
    login:
      host: "localhost"
    job:
      adapter: "linux_host"
      submit_host: "localhost"
      ssh_hosts:
        - localhost
      site_timeout: 7200
      debug: true
      singularity_bin: /usr/bin/singularity
      singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/users
      singularity_image: {{ singularity_image_dir }}/ubuntu-18.04.simg
      # Enabling strict host checking may cause the adapter to fail if the user's known_hosts does not have all the roundrobin hosts
      strict_host_checking: false

###
ood_master_sw_deps:
  - liblz4-tool
  - unzip
  - websockify
  - websockify-common

ood_client_sw_deps:
  - liblz4-tool
  - unzip
  - nmap
  - websockify
  - websockify-common
  - xfce4
  - xfce4-terminal
  - xfce4-goodies
  - gtk3-engines-xfce
  - jupyter-notebook
  - dbus-x11
  - firefox
  - cuda-nvvp-10-1
  - nvidia-visual-profiler
  - htop

ood_is_server: no
ood_is_client: no
