---
- name: Get on-board and container firmware versions
  shell: "docker run --privileged --rm -v /:/hostfs {{ firmware_update_repo }}:{{ firmware_update_tag }} show_version | tee {{ fw_dir }}/fw-versions.log"
  args:
    chdir: "{{ fw_dir }}"
  ignore_errors: yes
