---

- name: Make firmware dir
  file:
    path: "{{ fw_dir }}"
    state: directory

- include: load-image.yml

- include: update-firmware.yml
  vars:
    force_parameter: ''
  when: update_firmware

- include: run-diagnostics.yml
  when: run_diagnostics

- include: clean.yml