---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - numactl
  when: ansible_distribution == 'Ubuntu'

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - psmisc
    - numactl
  when: ansible_os_family == "RedHat"

- name: add cgroups to grub options
  lineinfile:
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub
  block:
    - name: update grub
      command: update-grub
    - name: reboot after updating grub config
      reboot:
  when: update_grub.changed and ansible_os_family == "Debian"

- name: update grub
  block:
    - name: update grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: reboot after updating grub config
      reboot:
  when: update_grub.changed and ansible_os_family == "RedHat"

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - /etc/slurm
    - /etc/slurm/shared
    - /etc/slurm/shared/bin
    - /var/log/slurm
    - /var/spool/slurm/d
  tags:
    - prolog
    - epilog

- name: copy shared scripts
  copy:
    src: "{{ item }}"
    dest: /etc/slurm/shared/bin/
    mode: 0755
  with_fileglob:
    - shared/bin/*
  tags:
    - prolog
    - epilog

- name: include prolog/epilog
  include: prolog_epilog.yml
  when: slurm_enable_prolog_epilog

- name: copy configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/slurm/{{ item }}"
  with_items:
    - slurm.conf
    - cgroup.conf
    - gres.conf
  notify:
    - restart slurmd
  tags:
    - config

- name: start slurmd
  systemd:
    name: slurmd
    state: started
    enabled: yes
    daemon-reload: yes

- name: install /etc/localusers
  template:
    src: etc-localusers
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /etc/slurm/localusers.backup
    - /etc/localusers
  tags:
    - localusers

- name: setup /etc/pam.d/sshd
  blockinfile:
    path: /etc/pam.d/sshd
    block: |
      -account sufficient pam_listfile.so item=user sense=allow file=/etc/localusers
      -account required {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config
