---
- name: install dependencies
  package:
    name: "{{ ood_client_sw_deps }}"
    state: present
  when: ood_client_sw_deps is defined

- name: install turbovnc
  apt:
    deb: https://downloads.sourceforge.net/project/turbovnc/2.2.3/turbovnc_2.2.3_amd64.deb
  tags:
    - vnc

- name: install codeserver
  unarchive:
    src: https://github.com/cdr/code-server/releases/download/2.1698/code-server2.1698-vsc1.41.1-linux-x86_64.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    exclude:
      - README.md
      - LICENSE.txt
      - ThirdPartyNotices.txt
    creates: /usr/local/bin/code-server
    mode: 0755
    extra_opts:
      - --strip-components=1
  tags:
    - codeserver
