---
- name: install dependencies
  package:
    name: "{{ ood_master_sw_deps }}"
    state: present
  when: ood_master_sw_deps is defined

- name: remove any existing OOD apps installed by ansible
  file:
    path: "{{ item.value.dest | default(ood_sys_app_dir) }}/{{ item.key }}"
    state: absent
  when: ood_install_apps is defined
  loop: "{{ ood_install_apps | default({}) | dict2items }}"

- name: install Open OnDemand
  include_role:
    name: ood-ansible

- name: create clusters dir
  file:
    path: "{{ ood_cluster_config_dir }}"
    state: directory
  tags:
    - configure

- name: configure slurm cluster connector
  template:
    src: cluster.yml.j2
    dest: "{{ ood_cluster_config_dir }}/{{ ood_cluster_name }}.yml"
  tags:
    - configure

- name: configure front page
  template:
    src: nginx_stage.yml.j2
    path: "/etc/ood/config/nginx_stage.yml"
  tags:
    - configure

- name: install package dependency for htpasswd module
  package:
    name: python-passlib
    state: present
  tags:
    - configure

- name: create .htpasswd entries
  htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ user }}"
    password: 'deepops'
    create: yes
  tags:
    - configure

- name: install required apache module
  apache2_module:
    state: present
    name: proxy_wstunnel
  register: mod_install
  tags:
    - configure

- name: restart apache after module install
  systemd:
    service: apache2
    state: restarted
  when: mod_install.changed
  tags:
    - configure

- name: create ssh key pair for default user
  openssh_keypair:
    path: "/home/{{ user }}/.ssh/id_rsa"
    owner: "{{ user }}"
  tags:
    - configure

- name: get ssh pub key
  slurp:
    src: "/home/{{ user }}/.ssh/id_rsa.pub"
  register: user_pub_key
  tags:
    - configure

- name: set ssh authorized key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ user_pub_key['content'] | b64decode }}"
  tags:
    - configure

- name: remove old desktop app config
  file:
    path: "{{ ood_desktop_app_dir }}/{{ item }}"
    state: absent
  with_items:
    - form.yml
      #- manifest.yml
      #- submit.yml.erb
      #- template/script.sh.erb
  tags:
    - configure

- name: create desktop app dir
  file:
    path: "{{ ood_desktops_dir }}"
    state: directory
  tags:
    - configure

- name: configure desktop
  template:
    src: desktop.yml.j2
    path: "{{ ood_desktops_dir }}/{{ ood_cluster_name }}.yml"
  tags:
    - configure

- name: configure desktop app submit
  template:
    src: desktop-submit.yml.erb.j2
    path: "{{ ood_desktops_dir }}/submit/{{ ood_cluster_name }}_desktop.yml.erb"
  tags:
    - configure

- name: configure desktop app form
  template:
    src: desktop-form.yml.j2
    path: "{{ ood_desktop_app_dir }}/form.yml"
  tags:
    - configure

- name: remove old config
  file:
    path: "{{ ood_codeserver_app_dir }}/{{ item }}"
    state: absent
  with_items:
    - form.yml
    - manifest.yml
    - submit.yml.erb
    - template/script.sh.erb
  tags:
    - configure

- name: configure vs code app form
  template:
    src: bc_osc_codeserver/form.yml.j2
    path: "{{ ood_codeserver_app_dir }}/form.yml"
  tags:
    - configure

- name: configure vs code app manifest
  template:
    src: bc_osc_codeserver/manifest.yml.j2
    path: "{{ ood_codeserver_app_dir }}/manifest.yml"
  tags:
    - configure

- name: configure vs code app submit
  template:
    src: bc_osc_codeserver/submit.yml.erb.j2
    path: "{{ ood_codeserver_app_dir }}/submit.yml.erb"
  tags:
    - configure

- name: configure vs code app script
  template:
    src: bc_osc_codeserver/script.sh.erb.j2
    path: "{{ ood_codeserver_app_dir }}/template/script.sh.erb"
    mode: 0755
  tags:
    - configure
