# NIS configuration
#nis_domain: example.com
#nis_server: 10.0.0.1

# Kerberos configuration
#kerberos_client_realm_name: "example.com"
#kerberos_client_kdc_hostname: "kerberos"
#kerberos_client_admin_hostname: "kerberos"
#nfs_idmapd_domain: example.com
