# Docker config
# Playbook: docker, nvidia-docker
docker_daemon_json:
  # Docker's default subnet is 172.17.0.0/16
  # Pick a smaller subnet, which is also less likely to conflict with corporate addresses.
  bip: 192.168.99.1/24

# Enroot configuration
# Playbook: slurm-perf, slurm-perf-cluster
enroot_runtime_path: '/tmp/enroot-runtime-$(id -u)'
enroot_cache_path: '/tmp/enroot-cache-$(id -u)'
enroot_data_path: '/tmp/enroot-data-$(id -u)'
enroot_config: |
  ENROOT_CONFIG_PATH ${HOME}/.config/enroot
  ENROOT_SQUASH_OPTIONS -noI -noD -noF -noX -no-duplicates
  ENROOT_MOUNT_HOME y
  ENROOT_RESTRICT_DEV y
  ENROOT_RUNTIME_PATH {{ enroot_runtime_path }}
  ENROOT_CACHE_PATH {{ enroot_cache_path }}
  ENROOT_DATA_PATH {{ enroot_data_path }}
enroot_environ_config_files:
  - filename: 50-mellanox.env
    content: |
      MELLANOX_VISIBLE_DEVICES=all
  - filename: 50-mpi.env
    content: |
      OMPI_MCA_btl_tcp_if_exclude=lo,docker0,ib0,ib1,ib2,ib3
