# Lmod modules
# Playbook: lmod
#lmod_modulepath: /shared/modules/all

# Extra software to install or remove
# Playbook: software
#software_extra_packages:
#  - curl
#  - git
#  - rsync
#  - screen
#  - tmux
#  - vim
#  - wget
#  - build-essential
#  - linux-tools-generic
#  - "{{ 'linux-headers-' + ansible_kernel }}"
#software_remove_packages:
#  - popularity-contest
