- name: check distro
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu'

- name: remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: unload nouveau
  modprobe:
    name: nouveau
    state: absent

- name: add key
  apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ repo_dir }}/7fa2af80.pub"
    id: 7fa2af80

- name: add repo
  apt_repository:
    repo: "deb http://developer.download.nvidia.com/compute/cuda/repos/{{ repo_dir }} /"
    update_cache: yes

- name: install driver packages
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - "{{ nvidia_driver_package_version | ternary('cuda-drivers='+nvidia_driver_package_version, 'cuda-drivers') }}"
  register: apt_install_driver

- name: create persistenced override dir
  file:
    path: /etc/systemd/system/nvidia-persistenced.service.d/
    state: directory
    recurse: yes

- name: configure persistenced service to turn on persistence mode
  copy:
    src: nvidia-persistenced-override.conf
    dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
  when: nvidia_driver_persistence_mode_on

- name: enable persistenced
  systemd:
    name: nvidia-persistenced
    enabled: yes

- name: reboot
  reboot:
  when: apt_install_driver.changed and not nvidia_driver_skip_reboot
