- name: check distro
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

- name: add epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: "https://epel.mirror.constant.com//RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  when: ansible_os_family == "RedHat"

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dkms
  when: ansible_os_family == "RedHat"

- name: remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: unload nouveau
  modprobe:
    name: nouveau
    state: absent

- name: add key
  apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ ubuntu_repo_dir }}/7fa2af80.pub"
    id: 7fa2af80
  when: ansible_distribution == "Ubuntu"

- name: add repo
  apt_repository:
    repo: "deb http://developer.download.nvidia.com/compute/cuda/repos/{{ ubuntu_repo_dir }} /"
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: add repo
  yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    gpgkey: "https://developer.download.nvidia.com/compute/cuda/repos/{{ rhel_repo_dir }}/7fa2af80.pub"
    baseurl: "https://developer.download.nvidia.com/compute/cuda/repos/{{ rhel_repo_dir }}/"
  when: ansible_os_family == "RedHat"

- name: install driver packages
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - "{{ nvidia_driver_package_version | ternary('cuda-drivers='+nvidia_driver_package_version, 'cuda-drivers') }}"
  register: install_driver
  when: ansible_distribution == "Ubuntu"

- name: install driver packages
  yum:
    name: "{{ item }}"
  with_items:
    - "{{ nvidia_driver_package_version | ternary('cuda-drivers='+nvidia_driver_package_version, 'cuda-drivers') }}"
  register: install_driver
  when: ansible_os_family == "RedHat"

- name: create persistenced override dir
  file:
    path: /etc/systemd/system/nvidia-persistenced.service.d/
    state: directory
    recurse: yes

- name: configure persistenced service to turn on persistence mode
  copy:
    src: nvidia-persistenced-override.conf
    dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
  when: nvidia_driver_persistence_mode_on

- name: remove persistenced service override
  file:
    path: /etc/systemd/system/nvidia-persistenced.service.d/override.conf
    state: absent
  when: not nvidia_driver_persistence_mode_on

- name: enable persistenced
  systemd:
    name: nvidia-persistenced
    enabled: yes

- name: check kernel versions
  yum:
    list: kernel
  register: yum_list
  when: ansible_os_family == "RedHat"

- name: register installed kernel version
  debug:
    msg: "{{ yum_list.results | selectattr('yumstate', 'equalto', 'installed') | list }}"
  register: kernel_version
  when: ansible_os_family == "RedHat"

- name: check kernel-headers versions
  yum:
    list: kernel-headers
  register: yum_list
  when: ansible_os_family == "RedHat"

- name: register installed kernel-headers version
  debug:
    msg: "{{ yum_list.results | selectattr('yumstate', 'equalto', 'installed') | list }}"
  register: kernel_headers_version
  when: ansible_os_family == "RedHat"

- name: update kernel if headers don't match
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel
    - kernel-tools
    - kernel-tools-libs
    - kernel-devel
    - kernel-debug-devel
    - kernel-headers
  register: kernel_update
  when: ansible_os_family == "RedHat" and (kernel_version.msg[0].release != kernel_headers_version.msg[0].release)

- name: reboot
  reboot:
  when: (install_driver.changed and not nvidia_driver_skip_reboot) or kernel_update.changed
