---
- name: remove packages
  apt:
    name:
      - nvidia-docker
    state: absent
    autoremove: yes
    purge: yes

- name: add key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: add repo
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/{{ ubuntu_repo_dist_name }}/{{ ubuntu_repo_file_name }}"
    dest: "{{ ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "nvidia-docker2{{ ubuntu_nvidia_docker2_package_version | ternary('='+ubuntu_nvidia_docker2_package_version, '') }}"
    - "nvidia-container-runtime{{ ubuntu_nvidia_container_runtime_package_version | ternary('='+ubuntu_nvidia_container_runtime_package_version, '') }}"
  register: install_packages

