---
- name: Install Docker and the NVIDIA container runtime
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker
    - "@NVIDIA container runtime"

- name: Install DGX System Management Tools
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python36
    - "@DGX System Management"
