---
- name: remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: add repo keys
  apt:
    deb: "{{ nvidia_dgx_ubuntu_gpgkey }}"

- name: add repo
  template:
    src: dgx.list.j2
    dest: /etc/apt/sources.list.d/dgx.list
    mode: 0644

- name: Install dgxserver-configurations meta package
  apt:
    name: "dgxserver-configurations"
    state: present
    update_cache: yes
