---
- name: create config dir
  file:
    path: "{{ prometheus_config_dir }}"
    state: directory
  when: is_prometheus_server

- name: create endpoints config dir
  file:
    path: "{{ prometheus_cfg_endpoint_dir }}"
    state: directory
  when: is_prometheus_server

- name: install config file
  template:
    src: templates/dcgm-exporter.yml.j2
    dest: "{{ prometheus_cfg_endpoint_dir }}/dcgm-exporter.yml"
    owner: root
    group: root
    mode: 0644
  when: is_prometheus_server

- name: install systemd unit file
  template:
    src: templates/docker.dcgm-exporter.service.j2
    dest: "/etc/systemd/system/{{ nvidia_dcgm_svc_name }}"
    owner: root
    group: root
    mode: 0644
  when: is_prometheus_client

- name: configure service
  systemd:
    name: "{{ nvidia_dcgm_svc_name }}"
    state: "{{ nvidia_dcgm_state }}"
    enabled: "{{ nvidia_dcgm_enabled }}"
    daemon_reload: yes
  notify: restart dcgm
  when: is_prometheus_client
