# Configuration common to all hosts
# Define per-group or per-host values in the other configuration files

# dns-config
#dns_config_servers: [8.8.8.8]
#dns_config_search: [example.com]

# NIS configuration
#nis_domain: example.com
#nis_server: 10.0.0.1

# Kerberos configuration
#kerberos_client_realm_name: "example.com"
#kerberos_client_kdc_hostname: "kerberos"
#kerberos_client_admin_hostname: "kerberos"
#nfs_idmapd_domain: example.com

# AutoFS configuration
#autofs_mount: "/home"
#autofs_map: "auto.home_linux"

# Slurm job scheduler configuration
#slurm_user_home: /local/slurm
#slurm_manage_gpus: true
#slurm_cluster_name: deepops
#slurm_username: slurm
#slurm_password: ReplaceWithASecurePasswordInTheVault
#slurm_db_username: slurm
#slurm_db_password: AlsoReplaceWithASecurePasswordInTheVault
#slurm_max_job_timelimit: INFINITE
#slurm_default_job_timelimit:

#nfs_exports:
#  - path: /export/shared
#    options: "*(rw,sync,no_root_squash)"

#nfs_mounts:
#  - mountpoint: /mnt/shared
#    server: '{{ groups["nfs-server"][0] }}'
#    path: /export/shared
#    options: async,vers=3

# Collectd
#collectd_network_server: "deepops-mgmt.example.com"
#collectd_network_port: "30300"
#collectd_python_module_path: "/usr/lib/collectd/dcgm"
#collectd_python_modules: []
#collectd_config_dir: "/etc/collectd/collectd.conf.d"
#with_dcgm_collectd: false

# Lmod modules
#lmod_modulepath: /shared/modules/all

# Extra software to install via software.yml playbook
#software_extra_packages:
#  - curl
#  - git
#  - rsync
#  - screen
#  - tmux
#  - vim
#  - wget
#  - build-essential
#  - linux-tools-generic
#  - "{{ 'linux-headers-' + ansible_kernel }}"

#software_remove_packages:
#  - popularity-contest

_cluster_repo_key_url: 'TODO'
_cluster_repo_key_id: 'TODO'
_cluster_repo: 'deb TODO /'

enroot_ubuntu_repo_key_url: "{{ _cluster_repo_key_url }}"
enroot_ubuntu_repo_key_id: "{{ _cluster_repo_key_id }}"
enroot_ubuntu_repo: "{{ _cluster_repo }}"

fuse_ubuntu_repo_key_url: "{{ _cluster_repo_key_url }}"
fuse_ubuntu_repo_key_id: "{{ _cluster_repo_key_id }}"
fuse_ubuntu_repo: "{{ _cluster_repo }}"

slurm_ubuntu_repo_key_url: "{{ _cluster_repo_key_url }}"
slurm_ubuntu_repo_key_id: "{{ _cluster_repo_key_id }}"
slurm_ubuntu_repo: "{{ _cluster_repo }}"

# software_packages_to_install:
#  - linux-headers-4.15.0-54-generic
#  - linux-image-4.15.0-54-generic
#  - linux-tools-4.15.0-54-generic

#software_packages_to_remove:
#  - 'linux-*-4.15.0-47-generic'
#  - 'linux-*-4.15.0-51-generic'
#  - 'linux-*-4.15.0-52-generic'
#  - 'linux-*-4.15.0-55-generic'
#  - 'linux-*-4.15.0-58-generic'
#  - linux-headers-generic
#  - linux-image-generic
#  - linux-tools-generic

enroot_runtime_path: '/tmp/enroot-runtime-$(id -u)'
enroot_cache_path: '/tmp/enroot-cache-$(id -u)'
enroot_data_path: '/tmp/enroot-data-$(id -u)'
