---
# DGX Server Configuration

# Collectd
collectd_python_modules:
  - dcgm_collectd
with_dcgm_collectd: true

# Docker Configuration
docker_daemon_json:
  default-runtime: nvidia
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
