---
# DGX Server Configuration

# cachefilesd
cachefilesd_cache_dir: /raid
cachefilesd_cache_tag: dgx1cache

# Collectd
collectd_python_modules:
  - dcgm_collectd
with_dcgm_collectd: true

# Docker Configuration
docker_daemon_json:
  default-runtime: nvidia
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
