---
# DGX Server Configuration

ansible_user: dgxuser

# Collectd
collectd_python_modules:
  - dcgm_collectd
with_dcgm_collectd: true

# Docker Configuration
docker_daemon_json:
  bip: 192.168.99.1/24
  default-runtime: nvidia
  insecure-registries:
    - "registry.local"
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
