---
# example usage:
# docker run --rm -ti --volume-driver=nfs -v <nfs_server>/prometheus:/mount ubuntu bash
- hosts: dgx-servers
  become: true
  become_method: sudo
  tasks:
    - name: package install
      apt:
        deb: https://github.com/ContainX/docker-volume-netshare/releases/download/v0.34/docker-volume-netshare_0.34_amd64.deb

    - name: configure settings
      lineinfile:
        path: /etc/default/docker-volume-netshare
        regexp: '^DKV_NETSHARE_OPTS='
        line: 'DKV_NETSHARE_OPTS="nfs -v 3"'

    - name: start service
      service:
        name: docker-volume-netshare
        state: started
        enabled: yes

