---

- hosts: all
  become: yes
  roles:
    - facts

- hosts: slurm-masters
  become: yes
  roles:
    - { role: ntp, is_controller: yes, is_compute: no}

- hosts: compute-nodes
  become: yes
  roles:
    - { role: ntp, is_compute: yes, is_controller: no }
