---
# mount volume
- hosts: all
  become: yes
  tasks:
    - name: dummy task
      shell: /bin/true
      register: gluster_vol_task
    - name: mount gluster volume
      mount:
        path: /shared
        src: "{{ ansible_hostname }}:/gv0"
        fstype: glusterfs
        state: mounted
      tags: gluster-vol
      when: gluster_vol_task is not defined


# install gluster
- hosts: all
  become: yes
  tasks:
    - name: install glusterfs packages
      action: apt name={{ item }} state=latest
      with_items:
        - software-properties-common
        - python-software-properties
    - name: add glusterfs ppa
      apt_repository:
        repo: 'ppa:gluster/glusterfs-3.13'
        update_cache: yes
- hosts: dgx-servers
  become: yes
  tasks:
    - name: add glusterfs packages
      apt:
        name: glusterfs-server
        state: latest
    - name: create data directory
      file:
        path: /raid/glusterfs-vol
        state: directory
        mode: 0700
    - name: run glusterd
      service:
        name: glusterd
        state: started
        enabled: yes
    - name: create gluster volume directory
      file:
        path: /raid/glusterfs-vol/gv0
        state: directory
    - name: create gluster volume directory
      file:
        path: /raid/glusterfs-vol/gv1
        state: directory
- hosts: slurm-masters
  become: yes
  tasks:
    - name: add glusterfs packages
      apt:
        name: glusterfs-client
        state: latest
