---
- hosts: all
  become: yes
  tasks:
    - name: remove resolvconf package
      apt:
        name: resolvconf
        state: absent
    - name: configure DNS nameservers
      lineinfile:
        path: /etc/resolv.conf
        firstmatch: yes
        insertbefore: '^nameserver'
        line: 'nameserver {{resolv_conf_nameserver}}'
