---
- name: install virtualenv
  apt:
    name:
     - "virtualenv"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: create location for python virtual env
  file:
    path: "{{ deepops_dir }}"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  pip:
    name: openshift
    virtualenv: "{{ deepops_venv }}"
  when: ansible_distribution == 'Ubuntu'

- name: install openshift python client for k8s_raw module
  yum:
    name: python2-openshift
  when: ansible_os_family == 'RedHat'
