# sudo docker run --rm -ti --net=host --privileged -v /mnt/:/iso:ro -e HOST_INT_PUB=ens160 -e HOST_INT_PRV=ens192 -e DEFAULT=DGX --name dgxie dgxie
# sudo docker run -d --name nfs --privileged --net=host -v /home/ubuntu/:/master -e SHARED_DIRECTORY=/master nfs-server:latest
version: '3'
services:
    dgxie:
        build: ~/dgxie
        network_mode: "host"
        privileged: true
        volumes:
            - /mnt/3.1.2:/iso:ro
        environment:
            - HOST_INT_PUB=eno1
            - HOST_INT_PRV=enxa0cec820063a
            - DEFAULT=DGX
            #- IP=192.168.1.1
            #- NETWORK=192.168.1.0
            #- NETMASK=255.255.255.0
            #- GATEWAY=192.168.1.1
            #- DNS1=8.8.8.8
            #- DNS2=8.8.4.4
            #- DHCP_START=192.168.1.2
            #- DHCP_END=192.168.254
    nfs-server:
        build: ~/nfs-server
        network_mode: "host"
        privileged: true
        volumes:
            - ~:/shared
        environment:
            - SHARED_DIRECTORY=/shared
