---
- name: Check MLNX NIC's
  shell: lspci | grep Mellanox | awk '{print $1}' | wc -l
  register: check_mlnx_adapter

- name: MOFED install
  block:
    - shell: |
        cd /tmp
        wget http://content.mellanox.com/ofed/{{ mofed_site_place }}/{{ mofed_file_name }}
        mkdir -p /mnt/iso
        mount -o loop /tmp/{{ mofed_file_name }} /mnt/iso
        /mnt/iso/mlnxofedinstall --all -q
      args:
        executable: /bin/bash
        warn: no
      register: install_mofed
    - reboot:
      when: install_mofed.changed
  when: check_mlnx_adapter.stdout|int > 0


