---
- name: add cgroups to grub options
  lineinfile:
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub (debian)
  block:
    - name: update grub
      command: update-grub
    - name: reboot after updating grub config
      reboot:
  when: update_grub.changed and ansible_os_family == "Debian"

- name: update grub (redhat)
  block:
    - name: update grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: reboot after updating grub config
      reboot:
  when: update_grub.changed and ansible_os_family == "RedHat"

- name: configure slurmd for pmix
  blockinfile:
    path: /etc/default/slurmd
    block: |
      PMIX_MCA_ptl=^usock
      PMIX_MCA_psec=none
      PMIX_SYSTEM_TMPDIR=/var/empty
      PMIX_MCA_gds=hash
  notify: restart slurmd
  tags: config

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - "{{ _spool_dir }}/d"
    - "{{ _log_dir }}"

- name: copy files to {{ _sysconf_dir }}
  template:
    src: "{{ item }}"
    dest: "{{ _sysconf_dir }}/"
  with_items:
    - etc/slurm/cgroup.conf
    - etc/slurm/gres.conf
  notify:
    - restart slurmd
  tags:
    - config

- name: start slurmd
  systemd:
    name: slurmd
    state: started
    enabled: yes
    daemon-reload: yes

- name: install /etc/localusers
  template:
    src: etc/localusers
    dest: /etc/localusers
    mode: 0600
  tags:
    - config

- name: setup /etc/pam.d/sshd
  blockinfile:
    path: /etc/pam.d/sshd
    block: |
      account sufficient pam_listfile.so item=user sense=allow file=/etc/localusers
      account required pam_slurm_adopt.so
    insertafter: "PAM configuration for the Secure Shell service"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config

- name: include prolog+epilog tasks
  include_tasks: prolog_epilog.yml
  tags: always
