---
- name: ubuntu vars
  include_vars:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: always

- name: rhel vars
  include_vars:
    file: rhel.yml
  when: ansible_os_family == 'RedHat'
  tags: always

- name: ubuntu tasks
  include: packages-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: redhat tasks
  include: packages-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: munge tasks
  include: munge.yml

- name: create slurm user home
  file:
   path: "{{ slurm_user_home }}"
   recurse: yes
   state: directory

- name: create slurm user
  user:
    name: slurm
    state: present
    system: yes
    home: "{{ slurm_user_home }}"
    uid: "{{ slurm_user_uid }}"

- name: copy slurm.conf
  template:
    src: etc/slurm/slurm.conf.j2
    dest: "{{ _sysconf_dir }}/slurm.conf"
  vars:
    default_config: "{{ lookup('template', 'etc/slurm/slurm.conf.defaults') }}"
    user_config: "{{ slurm_config | default('') }}"
  notify:
    - restart slurmctld
    - restart slurmdbd
    - restart slurmd
  tags: config

- include: controller.yml
  when: is_controller

- include: compute.yml
  when: is_compute

- include: shmfix.yml
  when: is_compute and slurm_fix_shm

- name: pyxis tasks
  include_tasks: pyxis.yml
  when: (is_controller or is_compute) and slurm_install_pyxis
  tags: pyxis
