---
- name: purge old slurm packages
  apt:
    name: slurm
    state: absent
    purge: yes

- name: purge old slurm package config files
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  with_items:
    - slurmctld.service
    - slurmd.service
    - slurmdbd.service
  notify: daemon reload

- name: repo key
  apt_key:
    url: "{{ slurm_ubuntu_repo_key_url }}"
    id: "{{ slurm_ubuntu_repo_key_id }}"

- name: repo
  apt_repository:
    repo: "{{ slurm_ubuntu_repo }}"

- name: shared packages
  apt:
    name: munge
  notify:
    - restart munge

- name: packages for client nodes
  apt:
    name:
      - nvslurm-utils

- name: packages for control node
  apt:
    name:
      - mariadb-server
      - python-mysqldb
      - python3-mysqldb
      - s-nail
      - nvslurm-control
      - nvslurm-database
      - ssmtp
  when: is_controller

- name: packages for compute nodes
  apt:
    name:
      - libhwloc-utils
      - libpam-slurm-adopt
      - linux-tools-generic  # for cpupower, used in prolog+epilog
      - nvslurm-compute
      - numactl
  when: is_compute

- name: packages for compute nodes with pyxis
  yum:
    name:
      - build-essential
      - libslurm-dev
  when: (is_controller or is_compute) and slurm_install_pyxis
  tags: pyxis
