---
# playbook for create NetworkAttachmentDefinition for Kubernetes Mellanox RDMA Device plugin in SRIOV mode
# #
# # Author: Vitaliy Razinkov <vitaliyra@mellanox.com>
# #
- name: Create netattdef
  k8s:
    state: present
    definition:
      apiVersion: "k8s.cni.cncf.io/v1"
      kind: NetworkAttachmentDefinition
      metadata:
        name: "{{ item.network_name }}"
        namespace: default
        annotations:
          k8s.v1.cni.cncf.io/resourceName: "{{ item.res_name }}"
      spec:
        config:
          '{
          type: "sriov",
          name: "{{ item.network_name }}",
          vlan: {{ item.vlan_id|int }},
          ipam: {
            type: "dhcp"
            }
          }'
  run_once: true
