
# Install Mellanox OFED
- import_playbook: mofed-install.yaml
  vars:
    mofed_site_place: "MLNX_OFED-4.6-1.0.1.1"
    mofed_file_name: "MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.iso"
  tags:
    - mellanox_ofed

#Install Mellanox GPUDirect
#- include: gpud-install.yaml
#  tags:
#    - gpudirect

#Install Mellanox device plugin for K8s
- import_playbook: k8s-sriov-device-plugin.yaml
  vars:
    config_json:
      resourceList:
      - resourceName: sriov_111
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - ens9f0
      - resourceName: sriov_112
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - ens10f0
      - resourceName: sriov_113
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - ens11f0
      - resourceName: sriov_114
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - ens12f0
  tags:
    - k8s_sriov_device_plugin

#Add network definition for vlan's
- name: Add NAD
  tasks:
    - include_tasks: nad4roce.yaml
      with_items:
        - { network_name: sriov111, res_name: intel.com/sriov_111, vlan_id: 111 }
        - { network_name: sriov112, res_name: intel.com/sriov_112, vlan_id: 112 }
        - { network_name: sriov113, res_name: intel.com/sriov_113, vlan_id: 113 }
        - { network_name: sriov114, res_name: intel.com/sriov_114, vlan_id: 114 }
  tags:
    - k8s_mlnx_network_definition
