---
# Install Mellanox OFED
- import_playbook: mofed-install.yaml
  vars:
    mofed_site_place: "MLNX_OFED-4.6-1.0.1.1"
    mofed_file_name: "MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.iso"
  tags:
    - mellanox_ofed

#Install Mellanox GPUDirect - WIP

# Activate VF for relevant PF
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: checking the Mellanox OFED is installed
      stat:
        path: /usr/bin/ofed_info
      register: ofed_present
    - include_tasks: vf-activate.yaml
      with_items:
        - "{{ pf1 }}"
        - "{{ pf2 }}"
        - "{{ pf3 }}"
        - "{{ pf4 }}"
      when: ofed_present.stat.exists
  tags:
    - vf_activation

#Install python dependencies
- hosts: kube-master
  tasks:
    - pip:
        name: openshift
    - name: check for module openshift
      python_requirements_facts:
        dependencies: 
          - openshift
  tags:
    - dep_openshift


#Download K8s SRIOV DP image
- hosts: kube-node
  tasks:
    - pip:
        name: docker-py
    - name: Pull docker image nfvpe/sriov-device-plugin
      docker_image: 
        name: "nfvpe/sriov-device-plugin"
        state: present
        pull: yes
  tags:
    - pull_k8s_dp_docker

#Install Mellanox device plugin for K8s
- import_playbook: k8s-sriov-device-plugin.yaml
  vars:
    config_json:
      resourceList:
      - resourceName: sriov_111
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - "{{ pf1 }}"
      - resourceName: sriov_112
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - "{{ pf2 }}"
      - resourceName: sriov_113
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - "{{ pf3 }}"
      - resourceName: sriov_114
        isRdma: true
        selectors:
          vendors:
          - 15b3
          devices:
          - 101c
          pfNames:
          - "{{ pf4 }}"
  tags:
    - k8s_sriov_device_plugin

#Install SRIOV CNI
- import_playbook: k8s-sriov-cni-ds.yaml

#Install DHCP CNI
- import_playbook: k8s-dhcp-cni-ds.yaml

#Add network definition for vlan's
- hosts: kube-master
  become: true
  become_method: sudo
  tasks:
    - include_tasks: nad4roce.yaml
      name: Add NAD
      with_items:
        - { network_name: sriov111, res_name: intel.com/sriov_111, vlan_id: 111 }
        - { network_name: sriov112, res_name: intel.com/sriov_112, vlan_id: 112 }
        - { network_name: sriov113, res_name: intel.com/sriov_113, vlan_id: 113 }
        - { network_name: sriov114, res_name: intel.com/sriov_114, vlan_id: 114 }
  tags:
    - k8s_mlnx_network_definition

#Install Kubeflow MPI-Operator:v1alpha2
- import_playbook: mpi-operator.yaml

