---
# playbook for VF activation after installing  Mellanox OFED
#
# Author: Vitaliy Razinkov <vitaliyra@mellanox.com>
#

- name: VF activation
  shell: |
    echo 8 > /sys/class/net/{{ item }}/device/sriov_numvfs
    sed -i '/^exit 0*/i echo 8 > /sys/class/net/{{ item }}/device/sriov_numvfs' /etc/rc.local
#  args:
#    executable: /bin/bash
#    warn: no    

