container_registry_version: 1.7.0
container_registry_hostname: registry.local
container_registry_ingress_enabled: true
container_registry_service_type: LoadBalancer
container_registry_storage_size: 100Gi
