install_from_src: false

ood_master_sw_deps:
  - lz4-devel
  - unzip
  - python-websockify

ood_client_sw_deps:
  - lz4-devel
  - unzip
  - nmap
  - python-websockify
  - '@xfce4'
  - python2-jupyter-core
  - python2-jupyroot
  - python36-jupyter-core
  - python36-jupyroot
  - dbus-x11
  - firefox
  - cuda-nvvp-10-1
