---
offline_cache_dir: "/tmp/deepops"
build_tar_file: true
tar_file_path: "/tmp/deepops-archive.tar.bz2"
deepops_repo_url: "https://github.com/NVIDIA/deepops"

# Flags
download_yum_repos: yes
download_docker_images: yes
download_helm_repos: yes
download_deepops_repo: yes

centos_iso_mirror: "http://mirrors.ocf.berkeley.edu/centos/7.6.1810/isos/x86_64"
centos_iso: "CentOS-7-x86_64-Minimal-1810.iso"
yum_repos_to_sync:
- "libnvidia-container"
- "nvidia-container-runtime"
- "nvidia-docker"
- "cuda"
#- "base"
#- "updates"
#- "extras"
#- "centosplus"
#- "docker-ce-stable"
#- "docker-engine"
#- "epel"

helm_download_url: "https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz"
helm_chart_git_repos:
  base: "https://github.com/helm/charts"
rook_helm_chart_url: "https://charts.rook.io/master/rook-ceph-v0.9.0-79.g1a1ffdd.tgz"

docker_http_timeout: 120
docker_image_list:
- name: "ceph"
  repo: ""
  image: "ceph/ceph"
  version: "v13.2.2-20181023"

- name: "coredns"
  repo: ""
  image: "coredns/coredns"
  version: "1.2.6"

- name: "addon-resizer-amd64"
  repo: "gcr.io/"
  image: "google-containers/addon-resizer-amd64"
  version: "2.1"

- name: "coredns"
  repo: "gcr.io/"
  image: "google-containers/coredns"
  version: "1.2.2"

- name: "kube-apiserver"
  repo: "gcr.io/"
  image: "google-containers/kube-apiserver"
  version: "v1.12.5"

- name: "kube-controller-manager"
  repo: "gcr.io/"
  image: "google-containers/kube-controller-manager"
  version: "v1.12.5"

- name: "kube-proxy"
  repo: "gcr.io/"
  image: "google-containers/kube-proxy"
  version: "v1.12.5"

- name: "pause"
  repo: "gcr.io/"
  image: "google-containers/pause"
  version: "3.1"

- name: "cluster-proportional-autoscaler-amd64"
  repo: "gcr.io/"
  image: "google_containers/cluster-proportional-autoscaler-amd64"
  version: "1.3.0"

- name: "kube-state-metrics"
  repo: "gcr.io/"
  image: "google_containers/kube-state-metrics"
  version: "v1.2.0"

- name: "kubernetes-dashboard-amd64"
  repo: "gcr.io/"
  image: "google_containers/kubernetes-dashboard-amd64"
  version: "v1.10.0"

- name: "pause-amd64"
  repo: "gcr.io/"
  image: "google_containers/pause-amd64"
  version: "3.1"

- name: "tiller"
  repo: "gcr.io/"
  image: "kubernetes-helm/tiller"
  version: "v2.11.0"

- name: "grafana"
  repo: ""
  image: "grafana/grafana"
  version: "5.0.0"

- name: "defaultbackend"
  repo: "k8s.gcr.io/"
  image: "defaultbackend"
  version: "1.4"

- name: "k8s-helm"
  repo: ""
  image: "lachlanevenson/k8s-helm"
  version: "v2.11.0"

- name: "controller"
  repo: ""
  image: "metallb/controller"
  version: "v0.7.3"

- name: "speaker"
  repo: ""
  image: "metallb/speaker"
  version: "v0.7.3"

- name: "nginx"
  repo: ""
  image: "nginx"
  version: "1.13"

- name: "dcgm-exporter"
  repo: "nvcr.io/"
  image: "nvidia/k8s/dcgm-exporter"
  version: "1.4.3"

- name: "k8s-device-plugin"
  repo: ""
  image: "nvidia/k8s-device-plugin"
  version: "1.11"

- name: "cni"
  repo: "quay.io/"
  image: "calico/cni"
  version: "v3.1.3"

- name: "ctl"
  repo: "quay.io/"
  image: "calico/ctl"
  version: "v3.1.3"

- name: "kube-controllers"
  repo: "quay.io/"
  image: "calico/kube-controllers"
  version: "v3.1.3"

- name: "node"
  repo: "quay.io/"
  image: "calico/node"
  version: "v3.1.3"

- name: "configmap-reload"
  repo: "quay.io/"
  image: "coreos/configmap-reload"
  version: "v0.0.1"

- name: "etcd"
  repo: "quay.io/"
  image: "coreos/etcd"
  version: "v3.2.24"

- name: "grafana-watcher"
  repo: "quay.io/"
  image: "coreos/grafana-watcher"
  version: "v0.0.8"

- name: "hyperkube"
  repo: "quay.io/"
  image: "coreos/hyperkube"
  version: "v1.7.6_coreos.0"

- name: "prometheus-config-reloader"
  repo: "quay.io/"
  image: "coreos/prometheus-config-reloader"
  version: "v0.20.0"

- name: "prometheus-operator"
  repo: "quay.io/"
  image: "coreos/prometheus-operator"
  version: "v0.20.0"

- name: "nginx-ingress-controller"
  repo: "quay.io/"
  image: "kubernetes-ingress-controller/nginx-ingress-controller"
  version: "0.22.0"

- name: "alertmanager"
  repo: "quay.io/"
  image: "prometheus/alertmanager"
  version: "v0.15.1"

- name: "node-exporter"
  repo: "quay.io/"
  image: "prometheus/node-exporter"
  version: "v0.15.2"

- name: "node-exporter"
  repo: "quay.io/"
  image: "prometheus/node-exporter"
  version: "v0.16.0"

- name: "prometheus"
  repo: "quay.io/"
  image: "prometheus/prometheus"
  version: "v2.2.1"

- name: "ceph"
  repo: ""
  image: "rook/ceph"
  version: "master"

- name: "ceph"
  repo: ""
  image: "rook/ceph"
  version: "v0.9.0-79.g1a1ffdd"

- name: "registry"
  repo: ""
  image: "registry"
  version: "latest"
