---
- name: apt update
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: restart cachefilesd
  service:
    name: cachefilesd
    state: restarted

- name: reboot after driver install
  reboot:
  when: install_driver.changed and not nvidia_driver_skip_reboot

