---
- name: ubuntu install tasks
  include_tasks: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: redhat family install tasks
  include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: install cuda
  package:
    name: "{{ cuda_version | default('cuda') }}"
    state: present

- name: add profile script to set environment for toolkit
  copy:
    src: "cuda-vars.sh"
    dest: "/etc/profile.d/cuda-vars.sh"
    owner: "root"
    group: "root"
    mode: "0644"
