---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: include default kubespray vars required for set_facts tasks
      include_vars: ../kubespray/roles/kubespray-defaults/defaults/main.yaml
    - name: include kubespray task to set facts required for docker role
      include: ../kubespray/roles/kubernetes/preinstall/tasks/0040-set_facts.yml

- hosts: all
  become: true
  become_method: sudo
  roles:
    - { role: kubespray-defaults }
    - { role: "../kubespray/roles/container-engine/docker" }
  environment: "{{proxy_env if proxy_env is defined else {}}}"
