---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  tasks:
    - name: include default kubespray vars required for set_facts tasks
      include_vars: ../kubespray/roles/kubespray-defaults/defaults/main.yaml
    - name: include kubespray task to set facts required for docker role
      include: ../kubespray/roles/kubernetes/preinstall/tasks/0040-set_facts.yml
    - name: remove docker overrides from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent

- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  roles:
    - { role: kubespray-defaults }
    - { role: "../kubespray/roles/container-engine/docker" }
  environment: "{{proxy_env if proxy_env is defined else {}}}"
  vars:
    # override deprecated dockerproject repo; old docker repo broken as of 03.04.2020
    dockerproject_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/$basearch/stable'
    dockerproject_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'
