---
## Random stuff that should be moved to ansible roles/playbooks
#
- hosts: slurm-cluster
  become: true
  roles:
    - { role: collectd, tags: collectd }
    #- prometheus-ipmi-exporter
  tasks:
    - name: install extra packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
      - direnv
      - tcsh
- hosts: dgx-servers
  become: true
  tasks:
    - name: enable and run dcgm service
      service:
        name: dcgm
        state: started
        enabled: yes
    - name: install dcgm collectd plugin
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
      - datacenter-gpu-manager-collectd
- hosts: slurm-masters
  become: true
  roles:
    - prometheus-slurm-exporter
  tasks:
    - name: stop and disable nv_peer_mem
      service:
        name: nv_peer_mem
        state: stopped
        enabled: no
    - name: stop and disable dcgm
      service:
        name: dcgm
        state: stopped
        enabled: no

- hosts: all
  become: true
  roles:
      #- { role: docker, when: with_local_apt == false, tags: docker }
    - { role: docker, tags: docker }
      #- {role: nvidia-docker2, when: with_local_apt}
      #- {role: singularity, when: with_local_apt}

