---

- hosts: kube-master
  become: true
  become_method: sudo
  tasks:
    - name: install pip
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "python-pip"
      when: (ansible_facts['distribution'] == 'Ubuntu')
    - name: install openshift python client for k8s_raw module
      pip:
        name: openshift
    - name: create GPU device plugin
      k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.12/nvidia-device-plugin.yml', split_lines=False) }}"
      run_once: true
  tags:
    - k8s_gpu_device_plugin
