---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    ansible_become: no
  tasks:
    - name: get GPU device plugin manifest
      get_url:
        url: https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.12/nvidia-device-plugin.yml
        dest: /tmp/nvidia-device-plugin.yml

- hosts: kube-master
  become: true
  become_method: sudo
  tasks:
    - name: install pip
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "python-pip"
      when: (ansible_facts['distribution'] == 'Ubuntu')
    - name: install openshift python client for k8s_raw module
      pip:
        name: openshift
    - name: get GPU device plugin manifest
      get_url:
        url: https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.12/nvidia-device-plugin.yml
        dest: /tmp/nvidia-device-plugin.yml
    - name: create GPU device plugin
      k8s:
        state: present
        definition: "{{ lookup('file', '/tmp/nvidia-device-plugin.yml') }}"
      run_once: true
    - name: remove GPU device plugin manifest
      file:
        path: /tmp/nvidia-device-plugin.yml
        state: absent

- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    ansible_become: no
  tasks:
    - name: remove GPU device plugin manifest
      file:
        path: /tmp/nvidia-device-plugin.yml
        state: absent
