---
# Install packages required for Ansible Helm module
- hosts: kube-master
  become: true
  tasks:
    - name: install package dependencies
      package:
        name:
          - python-pip
          - python-dev
          - libgit2-dev
          - gcc
          - git
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: install package dependencies
      package:
        name:
          - python2-pip
          - python36-pip
          - python-devel
          - libgit2-devel
          - gcc
          - git
        state: present
      when: ansible_os_family == 'RedHat'
    - name: install python dependencies
      pip:
        name:
          - pygit2==0.26
          - pyhelm
          - grpcio
          - requests==2.14.2
        state: present

# Docker container registry
- hosts: kube-master
  become: true
  tasks:
    - name: Install helm chart for container registry
      include_role:
        name: container-registry
      run_once: true
  tags:
    - container-registry

