---
- hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    pwgen: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
  tasks:
    - set_fact:
        passwd: "{{ pwgen }}"

- hosts: all
  become: true
  become_method: sudo
  vars:
    # User Configuration
    user_list:
      - name: "{{ ansible_user }}"
        username: "{{ ansible_user }}"
        state: present
        # You can also generate a password with `mkpasswd -m sha-512` and set that here
        password: "{{ passwd | password_hash('sha512', 'salty') }}"
        groups:
          - docker
  roles:
    - users 
  tasks:
    - debug:
       msg: "Set password to: {{ passwd }}"
