---
- hosts: all:!dgx-servers
  become: true
  tasks:
    - name: install custom facts
      include_role:
        name: facts

    - name: install nvidia driver
      include_role:
        name: nvidia-driver
      when: ansible_local['gpus']['count']

    - name: test nvidia-smi
      command: nvidia-smi
      changed_when: false
      when: ansible_local['gpus']['count']
