---
- hosts: all
  become: true
  tasks:
    - name: install custom facts module
      include_role:
        name: facts

    - name: install nvidia-docker
      include_role:
        name: nvidia-docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/ubuntu-bionic.yml
        nvidia_docker2_package_version: '2.0.3+docker18.06.1-1'
        nvidia_container_runtime_package_version: '2.0.0+docker18.06.1-1'
      when: ansible_local['gpus']['count'] and ansible_distribution == "Ubuntu"

    - name: install nvidia-docker
      include_role:
        name: nvidia-docker
      vars:
        # matches: kubespray/roles/container-engine/docker/vars/redhat.yml
        nvidia_docker2_package_version: '2.0.3-1.docker18.06.2'
        nvidia_container_runtime_package_version: '2.0.0-1.docker18.06.2'
      when: ansible_local['gpus']['count'] and ansible_os_family == "RedHat"
