---
- hosts: slurm-master
  tasks:
    - set_fact: slurm_node_is_controller=yes
      tags: always
- hosts: slurm-node
  tasks:
    - set_fact: slurm_node_is_compute=yes
      tags: always

- hosts: slurm-cluster
  become: yes
  tasks:
    - set_fact:
        enroot_environ_config_files:
        - filename: 50-mellanox.env
          content: |
            MELLANOX_VISIBLE_DEVICES=all
        - filename: 50-mpi.env
          content: |
            OMPI_MCA_btl_tcp_if_exclude=lo,docker0,ib0,ib1,ib2,ib3
      when: when: ansible_product_name is search("DGX")

- hosts: slurm-cluster
  become: yes
  roles:
    - name: ansible-role-enroot
    - name: pyxis
      vars:
        user: "{{ ansible_env.USER | default(ansible_env.SUDO_USER) }}"
        is_controller: (slurm_node_is_controller | default(False))
        is_compute: (slurm_node_is_compute | default(False))
        slurm_install_enroot: true
        slurm_install_pyxis: true
