---
# set gpu clocks on all worker nodes
- hosts: slurm-node
  gather_facts: no
  become: yes
  vars:
    gpu_clock_reset: yes
    gpu_clock: "1507,1507"
  tasks:
    - name: set the gpu clock to a specified amount
      shell: "nvidia-smi -lgc {{ gpu_clock }}"
      when: not gpu_clock_reset

    - name: reset the gpu clock to the default
      shell: "nvidia-smi -rgc"
      when: gpu_clock_reset
