---
# Deploy an optimized Slurm cluster

# Install Slurm optimizations
- include: slurm-cluster.yml
  vars:
    slurm_install_enroot: yes
    slurm_install_pyxis: yes

# Validate NCCL connectivity between all nodes in the cluster via enroot/pxysis/slurm
- include: slurm-validation.yml
