---
# Slurm Cluster Playbook

# Install python required for Ansible
- include: bootstrap-python.yml

# Set up passwordless sudo and SSH keys if needed
- include: bootstrap-ssh.yml
- include: bootstrap-sudo.yml

# Configure hostnames, /etc/hosts
- include: hosts.yml

# Configure Chrony (NTP) sync
- include: chrony-client.yml

# Install NVIDIA driver
- include: nvidia-driver.yml

# Install Docker and configure for NVIDIA
- include: docker.yml
  tags:
  - install_docker
- include: nvidia-docker.yml
  tags:
  - install_docker

# Install software
- include: software.yml

# Install Slurm
- include: slurm.yml

# Install OpenMPI
- include: openmpi.yml

# Install Singularity
- include: singularity.yml

# Install Open OnDemand
- include: open-ondemand.yml
  when: install_open_ondemand
