---

- hosts: all
  become: yes
  tasks:
    - name: install custom facts module
      include_role:
        name: facts
    - name: gather facts
      setup:

- hosts: slurm-masters
  become: yes
  tasks:
    - name: install slurm (mgmt node)
      include_role:
        name: slurm
      vars:
        user: "{{ ansible_user | default(ansible_env.SUDO_USER) }}"
        is_controller: yes

- hosts: compute-nodes
  become: yes
  tasks:
    - name: install slurm (compute node)
      include_role:
        name: slurm
      vars:
        user: "{{ ansible_user | default(ansible_env.SUDO_USER) }}"
        is_compute: yes
