---
- hosts: all
  become: yes
  roles:
    - name: facts

- hosts: slurm-masters
  become: yes
  roles:
    - name: slurm
      vars:
        user: "{{ ansible_user | default(ansible_env.SUDO_USER) }}"
        is_controller: yes

- hosts: slurm-workers
  become: yes
  roles:
    - name: slurm
      vars:
        user: "{{ ansible_user | default(ansible_env.SUDO_USER) }}"
        is_compute: yes
