---
- hosts: all
  become: true
  become_method: sudo
  vars:
    ssh_client_hardening: false
    ssh_server_password_login: true
    ssh_use_pam: true
    ssh_max_auth_retries: 10
  roles:
    - dev-sec.ssh-hardening
