---

- include: bootstrap-python.yml
- include: bootstrap-ssh.yml
- include: bootstrap-sudo.yml

- include: docker.yml
- include: nvidia-driver.yml
- include: nvidia-docker.yml
  vars:
    docker_daemon_json:
      bip: 192.168.99.1/24
      default-runtime: nvidia
      runtimes:
        nvidia:
          path: /usr/bin/nvidia-container-runtime
          runtimeArgs: []
