---
# Generate password for user
- hosts: all
  become: true
  gather_facts: false
  vars:
    pwgen: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
  tasks:
    - set_fact:
        passwd: "{{ pwgen }}"

- hosts: all
  become: true
  tasks:
    - name: Configure SSH to allow login with password
      include_role:
        name: dev-sec.ssh-hardening
      vars:
        ssh_client_hardening: false
        ssh_server_password_login: true
        ssh_use_pam: true
        ssh_max_auth_retries: 10
    - name: Set user password
      include_role:
        name: users
      vars:
        # User Configuration
        user_list:
          - name: "{{ ansible_user }}"
            username: "{{ ansible_user }}"
            state: present
            # You can also generate a password with `mkpasswd -m sha-512` and set that here
            password: "{{ passwd | password_hash('sha512', 'salty') }}"
            groups:
              - docker
    - debug:
       msg: "Set password for {{ ansible_user }} to: {{ passwd }}"
